services:
  loki:
    image: grafana/loki:latest
    container_name: steel-hammer-loki
    hostname: steel-hammer-loki
    user: "10001:10001"
    networks:
      - steel-hammer-network
    volumes:
      - loki-storage:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    restart: always

  mimir:
    image: grafana/mimir:latest
    container_name: steel-hammer-mimir
    hostname: steel-hammer-mimir
    networks:
      - steel-hammer-network
    volumes:
      - mimir-storage:/data
      - ./mimir-config.yaml:/etc/mimir/mimir.yaml
    command: -config.file=/etc/mimir/mimir.yaml
    restart: always

  tempo:
    image: grafana/tempo:2.9.0
    container_name: steel-hammer-tempo
    hostname: steel-hammer-tempo
    networks:
      - steel-hammer-network
    volumes:
      - tempo-storage:/var/tempo
      - ./tempo-config.yaml:/etc/tempo/tempo-config.yaml
    command: -config.file=/etc/tempo/tempo-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: steel-hammer-promtail
    hostname: steel-hammer-promtail
    networks:
      - steel-hammer-network
    depends_on:
      - loki
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: steel-hammer-grafana
    hostname: steel-hammer-grafana
    networks:
      - steel-hammer-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: steel-hammer-otel-collector
    hostname: steel-hammer-otel-collector
    networks:
      - steel-hammer-network
    command:
      - --config=/etc/otel-collector-config.yml
    environment:
      - GOGC=80
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - 4317:4317
      - 4318:4318
    restart: always

networks:
  steel-hammer-network:
    driver: bridge

volumes:
  loki-storage:
  mimir-storage:
  tempo-storage:
  grafana-storage:
